# Generated by Django 6.1 on 2026-08-26 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Nom complet / Entreprise')),
                ('phone', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Adresse email')),
                ('account_type', models.CharField(choices=[('PREPAID', 'Compte Prépayé (Acompte)'), ('CREDIT_MONTHLY', 'Client Conventionné (Facture Fin de Mois)')], default='PREPAID', max_length=32, verbose_name='Type de compte')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Solde actuel (Positif=Acompte, Négatif=Dette)')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Plafond de crédit autorisé (FCFA)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Compte actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant', verbose_name='Officine Propriétaire')),
            ],
            options={
                'verbose_name': 'Compte Client',
                'verbose_name_plural': 'Comptes Clients',
                'db_table': 'customers_customeraccount',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Dépôt / Recharge Acompte'), ('PURCHASE', 'Achat au comptoir (Débit)'), ('REFUND', 'Remboursement / Avoir'), ('PAYMENT_CREDIT', 'Règlement de facture impayée')], max_length=32, verbose_name="Type d'opération")),
                ('payment_method', models.CharField(choices=[('ESPECE', 'Espèces'), ('WAVE', 'Wave'), ('OMONEY', 'Orange Money'), ('CHEQUE', 'Chèque'), ('VIREMENT', 'Virement bancaire'), ('AUTRE', 'Autre')], default='ESPECE', max_length=32, verbose_name='Mode de règlement')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Solde après opération')),
                ('note', models.TextField(blank=True, default='', verbose_name='Commentaire / Motif')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='customers.customeraccount', verbose_name='Compte Client')),
            ],
            options={
                'verbose_name': 'Transaction Compte Client',
                'verbose_name_plural': 'Transactions Comptes Clients',
                'db_table': 'customers_customertransaction',
                'ordering': ['-created_at'],
            },
        ),
    ]
