# Generated by Django 6.1 on 2026-08-26 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('pos', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertransaction',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_transactions', to='pos.sale', verbose_name='Vente liée'),
        ),
        migrations.AddField(
            model_name='customertransaction',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant', verbose_name='Officine Propriétaire'),
        ),
        migrations.AddConstraint(
            model_name='customeraccount',
            constraint=models.UniqueConstraint(condition=models.Q(('phone', ''), _negated=True), fields=('tenant', 'phone'), name='unique_tenant_customer_phone'),
        ),
    ]
