# Generated by Django 6.1 on 2026-08-27 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_enable_rls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraccount',
            name='email',
        ),
        migrations.AlterField(
            model_name='customertransaction',
            name='payment_method',
            field=models.CharField(choices=[('ESPECE', 'Espèces'), ('WAVE', 'Wave'), ('OMONEY', 'Orange Money'), ('COMPTE_CLIENT', 'Compte Client'), ('CHEQUE', 'Chèque'), ('VIREMENT', 'Virement bancaire'), ('AUTRE', 'Autre')], default='ESPECE', max_length=32, verbose_name='Mode de règlement'),
        ),
    ]
