# Generated by Django 6.1 on 2026-08-26 09:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, verbose_name='Nom de la catégorie')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant', verbose_name='Officine Propriétaire')),
            ],
            options={
                'verbose_name': 'Catégorie de Dépense',
                'verbose_name_plural': 'Catégories de Dépenses',
                'db_table': 'billing_expensecategory',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant (FCFA)')),
                ('payment_method', models.CharField(choices=[('ESPECE', 'Espèces'), ('WAVE', 'Wave'), ('OMONEY', 'Orange Money'), ('CHEQUE', 'Chèque'), ('VIREMENT', 'Virement bancaire'), ('AUTRE', 'Autre')], default='ESPECE', max_length=32, verbose_name='Mode de paiement')),
                ('description', models.TextField(verbose_name='Description / Motif de la dépense')),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='expense_receipts/', verbose_name='Pièce justificative / Reçu')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Date de la dépense')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant', verbose_name='Officine Propriétaire')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='billing.expensecategory', verbose_name='Catégorie de dépense')),
            ],
            options={
                'verbose_name': "Dépense d'Exploitation",
                'verbose_name_plural': "Dépenses d'Exploitation",
                'db_table': 'billing_expense',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_tenant_expense_category'),
        ),
    ]
