# Generated by Django 6.1 on 2026-08-27 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_enable_rls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description / Motif de la dépense'),
        ),
    ]
