# Generated by Django 6.1 on 2026-08-26 09:43

import django.db.models.deletion
import django.utils.timezone
import tenancy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='PLAN UNIQUE PRO', max_length=100, verbose_name='Nom du Plan')),
                ('code', models.SlugField(default='standard_pro', max_length=64, unique=True, verbose_name='Code du Plan')),
                ('description', models.TextField(blank=True, default='Plan tout-en-un: POS, Stocks FEFO, Comptes Clients, Fournisseurs et États Financiers.', verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, default=30000.0, max_digits=12, verbose_name='Tarif mensuel (FCFA)')),
                ('duration_days', models.PositiveIntegerField(default=30, verbose_name='Durée par défaut (jours)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Plan disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Plan d'Abonnement",
                'verbose_name_plural': "Plans d'Abonnement",
                'db_table': 'subscription_plans',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.CharField(default=tenancy.models.generate_tenant_id, editable=False, max_length=16, primary_key=True, serialize=False, verbose_name='ID Officine (Tenant ID)')),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'Officine")),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='Code unique')),
                ('license_number', models.CharField(blank=True, default='', max_length=128, verbose_name="Numéro d'agrément / Licence")),
                ('phone', models.CharField(blank=True, default='', max_length=64, verbose_name='Téléphone')),
                ('address', models.TextField(blank=True, default='', verbose_name='Adresse physique')),
                ('city', models.CharField(blank=True, default='Dakar', max_length=128, verbose_name='Ville')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='pharmacy_logos/', verbose_name='Logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Officine active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Officine (Tenant)',
                'verbose_name_plural': 'Officines (Tenants)',
                'db_table': 'tenants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TenantSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('TRIAL', "Période d'essai"), ('ACTIVE', 'Actif'), ('EXPIRED', 'Expiré'), ('SUSPENDED', 'Suspendu')], default='TRIAL', max_length=32, verbose_name='Statut')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de début')),
                ('end_date', models.DateTimeField(verbose_name='Date de fin / Expiration')),
                ('is_active', models.BooleanField(default=True, verbose_name='Abonnement actif')),
                ('notes', models.TextField(blank=True, default='', verbose_name="Notes de l'administrateur SaaS")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='tenancy.subscriptionplan', verbose_name='Plan')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenancy.tenant', verbose_name='Officine')),
            ],
            options={
                'verbose_name': 'Abonnement Officine',
                'verbose_name_plural': 'Abonnements Officines',
                'db_table': 'tenant_subscriptions',
            },
        ),
    ]
