# Generated by Django 6.1 on 2026-08-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='auto_print',
            field=models.BooleanField(default=False, verbose_name='Impression automatique des reçus'),
        ),
    ]
