# Generated by Django 6.1 on 2026-08-26 09:45

import apps.suppliers.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, default=apps.suppliers.models.generate_order_number, max_length=64, verbose_name='Numéro de Commande')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon / Proposition'), ('EXPORTED', 'Exporté / Envoyé au grossiste'), ('RECEIVED', 'Livré & Réceptionné'), ('CANCELLED', 'Commande Annulée')], db_index=True, default='DRAFT', max_length=16, verbose_name='Statut')),
                ('total_amount_ht', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Montant total estimé HT (FCFA)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes / Instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant', verbose_name='Officine Propriétaire')),
            ],
            options={
                'verbose_name': 'Bon de Commande Fournisseur',
                'verbose_name_plural': 'Bons de Commande Fournisseurs',
                'db_table': 'suppliers_purchaseorder',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.PositiveIntegerField(verbose_name='Quantité commandée')),
                ('quantity_received', models.PositiveIntegerField(default=0, verbose_name='Quantité reçue')),
                ('unit_purchase_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name="Prix unitaire d'achat HT (FCFA)")),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='suppliers.purchaseorder', verbose_name='Bon de commande')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='inventory.pharmacyproduct', verbose_name='Produit')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant', verbose_name='Officine Propriétaire')),
            ],
            options={
                'verbose_name': 'Ligne de Commande Fournisseur',
                'verbose_name_plural': 'Lignes de Commande Fournisseur',
                'db_table': 'suppliers_purchaseorderitem',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Nom du grossiste / Fournisseur')),
                ('phone', models.CharField(blank=True, default='', max_length=64, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email commercial')),
                ('address', models.TextField(blank=True, default='', verbose_name='Adresse')),
                ('contact_person', models.CharField(blank=True, default='', max_length=128, verbose_name='Nom du délégué / contact')),
                ('order_website_url', models.URLField(blank=True, default='', verbose_name='Portail de commande en ligne')),
                ('is_active', models.BooleanField(default=True, verbose_name='Fournisseur actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant', verbose_name='Officine Propriétaire')),
            ],
            options={
                'verbose_name': 'Fournisseur Grossiste',
                'verbose_name_plural': 'Fournisseurs Grossistes',
                'db_table': 'suppliers_supplier',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='suppliers.supplier', verbose_name='Fournisseur Grossiste'),
        ),
        migrations.CreateModel(
            name='SupplierClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_type', models.CharField(choices=[('EXPIRED_RECEIVED', 'Produit reçu périmé ou proche péremption'), ('MISSING_ITEM', 'Produit facturé mais manquant'), ('WRONG_PRODUCT', 'Erreur de produit livré (Non conforme)'), ('DAMAGED', 'Produit cassé / Emballage détérioré')], max_length=32, verbose_name='Motif de réclamation')),
                ('product_name', models.CharField(max_length=255, verbose_name='Nom du produit concerné')),
                ('batch_number', models.CharField(blank=True, default='', max_length=64, verbose_name='N° de lot concerné')),
                ('quantity_affected', models.PositiveIntegerField(verbose_name='Quantité défectueuse / manquante')),
                ('description', models.TextField(verbose_name='Explication détaillée du litige')),
                ('photo_proof', models.ImageField(blank=True, null=True, upload_to='claim_proofs/', verbose_name='Photo justificative')),
                ('status', models.CharField(choices=[('PENDING', 'En attente de traitement'), ('ACCEPTED', 'Réclamation acceptée par le grossiste'), ('REFUNDED', 'Avoir / Remboursement émis'), ('REJECTED', 'Réclamation rejetée')], db_index=True, default='PENDING', max_length=16, verbose_name='Statut du litige')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Déclaré par')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='suppliers.purchaseorder', verbose_name='Commande liée (optionnelle)')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='suppliers.supplier', verbose_name='Fournisseur concerné')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant', verbose_name='Officine Propriétaire')),
            ],
            options={
                'verbose_name': 'Réclamation Fournisseur',
                'verbose_name_plural': 'Réclamations Fournisseurs',
                'db_table': 'suppliers_supplierclaim',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(fields=('tenant', 'order_number'), name='unique_tenant_purchase_order'),
        ),
    ]
