# Generated by Django 6.1 on 2026-08-27 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_enable_rls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='email',
        ),
    ]
