# Generated by Django 6.1 on 2026-08-26 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, max_length=64, verbose_name='Code-barres principal (Code 1)')),
                ('alternate_barcode', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Code-barres secondaire (Code 2)')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Désignation / Nom du produit')),
                ('shelf_location', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Emplacement / Code géo / Rayon')),
                ('purchase_price_ht', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name="Prix unitaire d'achat HT (FCFA)")),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix unitaire de vente TTC (FCFA)')),
                ('tva_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Taux TVA (%)')),
                ('reorder_threshold', models.PositiveIntegerField(default=10, verbose_name="Seuil d'alerte réapprovisionnement")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif en vente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_products', to='catalog.medicamentcatalog', verbose_name='Référence Catalogue National')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant', verbose_name='Officine Propriétaire')),
            ],
            options={
                'verbose_name': "Produit de l'Officine",
                'verbose_name_plural': "Produits de l'Officine",
                'db_table': 'inventory_pharmacyproduct',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(db_index=True, max_length=64, verbose_name='Numéro de lot')),
                ('expiration_date', models.DateField(db_index=True, verbose_name='Date de péremption')),
                ('quantity_received', models.IntegerField(default=0, verbose_name='Quantité initiale reçue')),
                ('quantity_current', models.IntegerField(default=0, verbose_name='Quantité actuelle disponible')),
                ('is_active', models.BooleanField(default=True, verbose_name='Lot actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.pharmacyproduct', verbose_name='Produit')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant', verbose_name='Officine Propriétaire')),
            ],
            options={
                'verbose_name': 'Lot de Produit',
                'verbose_name_plural': 'Lots de Produits',
                'db_table': 'inventory_productbatch',
                'ordering': ['expiration_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN_IMPORT', 'Importation initiale CSV'), ('IN_PURCHASE', 'Réception commande fournisseur'), ('OUT_SALE', 'Vente au comptoir (POS)'), ('ADJUSTMENT_IN', 'Ajustement inventaire positif'), ('ADJUSTMENT_OUT', 'Ajustement inventaire négatif'), ('LOSS_EXPIRED', 'Perte produit périmé'), ('LOSS_DAMAGED', 'Casse / Produit détérioré'), ('OUT_RETURN_SUPPLIER', 'Retour fournisseur')], max_length=32, verbose_name='Type de mouvement')),
                ('quantity', models.IntegerField(verbose_name='Quantité (+/-)')),
                ('reference_doc', models.CharField(blank=True, default='', max_length=128, verbose_name='N° Pièce / Référence')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes / Motif')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.productbatch', verbose_name='Lot concerné')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Effectué par')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.pharmacyproduct', verbose_name='Produit')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant', verbose_name='Officine Propriétaire')),
            ],
            options={
                'verbose_name': 'Mouvement de Stock',
                'verbose_name_plural': 'Mouvements de Stock',
                'db_table': 'inventory_stockmovement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='pharmacyproduct',
            constraint=models.UniqueConstraint(fields=('tenant', 'barcode'), name='unique_tenant_product_barcode'),
        ),
        migrations.AddConstraint(
            model_name='productbatch',
            constraint=models.UniqueConstraint(fields=('tenant', 'product', 'batch_number'), name='unique_tenant_product_batch'),
        ),
    ]
