# Generated by Django 6.1 on 2026-08-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicamentCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Code-barres / Code CIP (EAN-13)')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Nom commercial')),
                ('dci', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='DCI (Dénomination Commune Internationale)')),
                ('form_dosage', models.CharField(blank=True, default='', max_length=255, verbose_name='Forme galénique & Dosage')),
                ('default_category', models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='Famille thérapeutique')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif au catalogue')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Médicament du Catalogue National',
                'verbose_name_plural': 'Catalogue National des Médicaments',
                'db_table': 'medicament_catalog',
                'ordering': ['name'],
            },
        ),
    ]
