# Generated by Django 6.1 on 2026-08-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamentcatalog',
            name='alternate_barcode',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Code 2 / Code alternatif'),
        ),
        migrations.AddField(
            model_name='medicamentcatalog',
            name='geo_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='Code géo / Rayon indicatif'),
        ),
        migrations.AlterField(
            model_name='medicamentcatalog',
            name='barcode',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Code 1 / Code-barres principal (EAN-13/CIP)'),
        ),
        migrations.AlterField(
            model_name='medicamentcatalog',
            name='default_category',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='Famille thérapeutique (Optionnelle)'),
        ),
        migrations.AlterField(
            model_name='medicamentcatalog',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Label / Nom commercial'),
        ),
    ]
