# Generated by Django 6.1 on 2026-08-26 09:46

import common.utils
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Date de session')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Ouverte à')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Clôturée à')),
                ('initial_cash', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Fonds de caisse initial (FCFA)')),
                ('expected_cash', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total théorique espèces attendu (FCFA)')),
                ('actual_cash_counted', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Espèces réelles comptées (FCFA)')),
                ('cash_difference', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Écart de caisse (FCFA)')),
                ('status', models.CharField(choices=[('OPEN', 'Session Ouverte'), ('CLOSED', 'Session Clôturée')], db_index=True, default='OPEN', max_length=16, verbose_name='Statut de la session')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observations')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Caissier / Responsable')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant', verbose_name='Officine Propriétaire')),
            ],
            options={
                'verbose_name': 'Session de Caisse',
                'verbose_name_plural': 'Sessions de Caisse',
                'db_table': 'pos_cashsession',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(db_index=True, default=common.utils.generate_ticket_number, max_length=64, verbose_name='Numéro de Ticket')),
                ('total_ht', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total HT')),
                ('total_tva', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total TVA')),
                ('total_ttc', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total TTC à payer (FCFA)')),
                ('payment_method', models.CharField(choices=[('ESPECE', 'Espèces'), ('WAVE', 'Wave'), ('OMONEY', 'Orange Money'), ('COMPTE_CLIENT', 'Compte Client'), ('MIXTE', 'Paiement Mixte'), ('CARTE_BANCAIRE', 'Carte Bancaire'), ('CHEQUE', 'Chèque')], default='ESPECE', max_length=32, verbose_name='Mode de paiement')),
                ('amount_received', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Montant reçu')),
                ('change_returned', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monnaie rendue')),
                ('status', models.CharField(choices=[('PAID', 'Payé'), ('CREDIT', 'Vente à crédit'), ('CANCELLED', 'Ticket Annulé')], db_index=True, default='PAID', max_length=16, verbose_name='Statut du ticket')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cash_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='pos.cashsession', verbose_name='Session de Caisse')),
                ('cashier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='Caissier')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='customers.customeraccount', verbose_name='Compte Client')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant', verbose_name='Officine Propriétaire')),
            ],
            options={
                'verbose_name': 'Vente / Ticket de Caisse',
                'verbose_name_plural': 'Ventes / Tickets de Caisse',
                'db_table': 'pos_sale',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantité vendue')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix unitaire (FCFA)')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total ligne (FCFA)')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='inventory.productbatch', verbose_name='Lot décrémenté (FEFO)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='inventory.pharmacyproduct', verbose_name='Produit')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.sale', verbose_name='Vente liée')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant', verbose_name='Officine Propriétaire')),
            ],
            options={
                'verbose_name': 'Ligne de Vente',
                'verbose_name_plural': 'Lignes de Vente',
                'db_table': 'pos_saleitem',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(fields=('tenant', 'ticket_number'), name='unique_tenant_sale_ticket'),
        ),
    ]
