# Generated by Django 6.1 on 2026-08-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_enable_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_details',
            field=models.JSONField(blank=True, default=list, verbose_name='Détail des paiements (Paiement mixte)'),
        ),
    ]
